---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "TJC Livestreams"
keywords:    "true jesus church, tjc, livestreams, streams"
description: "Find all the available tjc livestreams here"
source_link: "https://github.com/huangkaiw3n/tjc-livestreams"
favicon:     "img/favicon.png"
touch_icon:  "img/apple-touch-icon.png"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

